linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: false
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 150
  misspell:
    locale: US
  lll:
    line-length: 200
  goconst:
    min-len: 3
    min-occurrences: 5
  funlen:
    lines: 150
    statements: 80
  gosec:
    excludes:
      - G306  # File permissions

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - errcheck
    - misspell
    - goconst
    - dupl
    - lll
    - unconvert
    - gocyclo
    - funlen
    - revive
    - gosec
    - exportloopref
    - whitespace
    - structcheck
    - varcheck
    - deadcode
    - ifshort

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
